### PR TITLE
Make hover color a bit lighter

### PR DESCRIPTION
**Pull request by hansnn**
The new color isn't in the color palette, so I just added it directly

### CODE REVIEW

**Comment by kyryl-bogach** [comment]
Should we add the color to the palette though?

**Comment by hansnn** [comment]
Since it's not already in the Figma palette my assumption is that this color doesn't really follow our design patterns, but is just a "quick-fix" to have some kind of hover color on web. So not sure if it gives us value to have it in the palette or not. I guess it's up to JP in the end

**Comment by hansnn** [comment]
Updated to use the color that JP provided

**Review by kyryl-bogach — APPROVED** [review]
🚀

**Pull request merged**
